apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: "https://hooks.slack.com/services/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"
